site_name: Drawer Where I keep my dev notes.
site_url: https://ronnyhdez.github.io/drawer/
site_author: Ronny A. Hernández Mora
repo_url: https://github.com/ronnyhdez/drawer
repo_name: ronnyhdez/drawer
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ronny_hdezmora
      name: Ronny on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ronny-hernandez-mora/
      name: Ronny on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/ronnyhdez
      name: Ronny on GitHub
theme:
   name: material
   extra_css:
     docs/extra.css 
   font:
     text: Open Sans
   favicon: images/pencil.png
   logo: images/pen-to-square-regular.svg
   palette: 
     primary: deep orange 
markdown_extensions:
   - toc:
      permalink: []
