site_name: Drawer Where I keep my R notes (and other dev stuff)
site_url: https://ronnyhdez.github.io/drawer/
site_author: Ronny A. Hernández Mora
repo_url: https://github.com/ronnyhdez/drawer
repo_name: ronnyhdez/drawer
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ronny_hdezmora
      name: Ronny on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ronny-hernandez-mora/
      name: Ronny on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/ronnyhdez
      name: Ronny on GitHub
theme:
   name: material
   font:
     text: Inconsolata
   favicon: images/pencil.png
   logo: images/pen-to-square-regular.svg
   palette: 
     primary: deep orange 
markdown_extensions:
   - toc:
      permalink: []
